version: "3.9"

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin 
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: host.docker.internal   # ← ชี้มาที่ MariaDB ในเครื่อง macOS
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""
